# Use k-Means to Cluster Foods Based on Nutrients

In [ ]:
!pip install kmeans-pytorch

Collecting kmeans-pytorch
  Downloading kmeans_pytorch-0.3-py3-none-any.whl.metadata (1.6 kB)
Downloading kmeans_pytorch-0.3-py3-none-any.whl (4.4 kB)
Installing collected packages: kmeans-pytorch
Successfully installed kmeans-pytorch-0.3

In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import torch
from sklearn.preprocessing import StandardScaler



pd.options.display.max_rows = 200
pd.options.display.min_rows = 30
pd.options.display.max_seq_items = None
np.random.seed(222)

In [ ]:
# link drive
from google.colab import drive
drive.mount('/content/drive')
share_path = "/content/drive/MyDrive/Colab_Notebooks/deeplearning2026"
import os
print(os.listdir(share_path))

Mounted at /content/drive
['documentation', 'notebooks', 'NLP-Arch.gdoc', 'Siavash', 'data']

In [ ]:
data_path = share_path + '/data/'
df = pd.read_parquet(data_path + 'FDCkmeansclustered.parquet.gzip')
df.columns

Index(['description', 'ALA_G', 'ARA_G', 'B12_UG', 'B1_MG', 'B2_MG', 'B3_MG',
       'B5_MG', 'B6_MG', 'B7_UG', 'B9_UG', 'B_UG', 'CHO1_G', 'CHOfiber1_G',
       'CHOstarch_G', 'CHOsugar_G', 'Ca_MG', 'Cl_MG', 'Co_UG', 'Cr_UG',
       'Cu_MG', 'DHA_G', 'DPA_G', 'EPA_G', 'F_UG', 'Fe_MG', 'I_UG', 'K_MG',
       'MUFA_G', 'Mg_MG', 'Mn_MG', 'Mo_UG', 'Na_MG', 'Ni_UG', 'PUFA_G', 'P_MG',
       'S_MG', 'Se_UG', 'Zn_MG', 'alanine_G', 'alcohol_G', 'arginine_G',
       'aspartate_G', 'caffeine_MG', 'category', 'cholesterol_MG',
       'cysteine_G', 'cystine_G', 'data_type', 'fructose_G', 'glucose_G',
       'glutamate_G', 'glycine_G', 'histidine_G', 'hydroxyproline_G',
       'insol_fiber_G', 'isoleucine_G', 'kcal1_KCAL', 'lactose_G', 'leucine_G',
       'lycopene_UG', 'lysine_G', 'maltose_G', 'methionine_G',
       'phenylalanine_G', 'proline_G', 'protein_G', 'pufa_18_2_n6_G',
       'pufa_18_3_n6_G', 'pufa_20_2_n6_G', 'pufa_20_3_n3_G', 'pufa_20_3_n6_G',
       'pufa_20_4_G', 'sat_fat_G', 'serine_G', 'sol_fiber_G', 'sucrose_G',
       'taurine_G', 'threonine_G', 'total_choline_MG', 'total_fat_G',
       'total_vit_d_IU', 'total_vit_d_UG', 'total_vit_e_mg', 'trans_fat_G',
       'tryptophan_G', 'tyrosine_G', 'valine_G', 'vit_a_IU', 'vit_c_MG',
       'vit_k_UG', 'water_G', 'text', 'embeddings', 'k15', 'k18', 'k21', 'k24',
       'k27', 'k30', 'k30names'],
      dtype='object')

## Remove excessive missing values

In [ ]:
df.notna().sum(axis=1).describe()

count    487227.000000
mean         25.630012
std           6.897991
min          12.000000
25%          25.000000
50%          25.000000
75%          26.000000
max          88.000000
dtype: float64

In [ ]:
# a lot of missing values
# remove observations with fewer than 'required' non-missing values
print(df.shape[0])
required = 25  # will remove ~25% of sample
X = df.loc[df.notna().sum(axis=1) >= required,]
print(X.shape[0])

487227
372592

In [ ]:
# now look at columns with a lot of missing values
n = (X.isna().sum() * 100 / X.shape[0]).sort_values()
print(n)

description          0.000000
k24                  0.000000
k27                  0.000000
k30                  0.000000
text                 0.000000
embeddings           0.000000
k15                  0.000000
k30names             0.000000
k21                  0.000000
k18                  0.000000
data_type            0.027913
total_fat_G          0.053141
category             0.104404
protein_G            0.119702
Na_MG                0.311869
CHO1_G               0.334414
Ca_MG                0.369573
Fe_MG                0.388092
CHOfiber1_G          0.571134
sat_fat_G            0.611393
kcal1_KCAL           0.662924
cholesterol_MG       0.677953
trans_fat_G          3.182570
K_MG                39.020967
vit_c_MG            39.530103
vit_a_IU            44.086561
total_vit_d_IU      57.888521
MUFA_G              80.137791
PUFA_G              80.163020
total_vit_d_UG      80.495555
B3_MG               89.292577
B1_MG               89.431335
B2_MG               89.575729
B6_MG               91.884152
P_MG                92.001439
Mg_MG               92.037671
B9_UG               92.544392
Zn_MG               92.680465
B12_UG              93.034204
Cu_MG               94.678093
Se_UG               95.541772
water_G             95.709248
total_vit_e_mg      96.067817
vit_k_UG            96.162290
Mn_MG               96.275014
B5_MG               96.571853
pufa_20_4_G         96.823335
EPA_G               96.954309
DHA_G               96.961824
DPA_G               96.966118
caffeine_MG         97.053077
alcohol_G           97.082063
lycopene_UG         97.096556
total_choline_MG    97.177878
sol_fiber_G         98.513119
lysine_G            98.563845
methionine_G        98.564113
valine_G            98.567870
isoleucine_G        98.567870
threonine_G         98.568676
phenylalanine_G     98.568676
leucine_G           98.569212
histidine_G         98.569481
arginine_G          98.576459
tryptophan_G        98.583437
tyrosine_G          98.583706
serine_G            98.588805
alanine_G           98.588805
glycine_G           98.589073
glutamate_G         98.589342
proline_G           98.590415
insol_fiber_G       98.610545
aspartate_G         98.630674
cystine_G           98.638725
pufa_20_2_n6_G      99.316410
I_UG                99.331709
lactose_G           99.421083
CHOstarch_G         99.439601
ALA_G               99.449532
pufa_18_2_n6_G      99.478250
fructose_G          99.487375
glucose_G           99.488985
sucrose_G           99.491132
maltose_G           99.496500
Mo_UG               99.505625
pufa_18_3_n6_G      99.537564
B7_UG               99.588021
hydroxyproline_G    99.602514
pufa_20_3_n6_G      99.642504
pufa_20_3_n3_G      99.705576
Cr_UG               99.758449
B_UG                99.779383
Ni_UG               99.779383
S_MG                99.779383
Co_UG               99.779383
CHOsugar_G          99.797365
Cl_MG               99.843529
F_UG                99.854801
ARA_G               99.955716
cysteine_G          99.975577
taurine_G           99.995974
dtype: float64

In [ ]:
# data frame with less than 90% missing in each column
X = X.drop(n.index[n >= 90], axis = 1)
print(X.shape)

(372592, 33)

## Scale data and remove labels

In [ ]:
X_labels = X[['description','data_type','category']].copy()
X.drop(['description','data_type','category','k24','k27',
        'k30','text','embeddings','k15','k30names','k21','k18'],
       axis = 1, inplace = True)
print(X)
scaler = StandardScaler()
X = scaler.fit_transform(X)

        B1_MG  B2_MG  B3_MG  CHO1_G  CHOfiber1_G  Ca_MG  Fe_MG   K_MG  MUFA_G  \
1         NaN    NaN    NaN    8.24          0.0    0.0   0.85    NaN     NaN
2         NaN    NaN    NaN   78.26          2.2   22.0   3.04   87.0     NaN
3         NaN    NaN    NaN    3.33          0.4   42.0   0.15   75.0   0.620
4         NaN    NaN    NaN    3.33          0.4   42.0   0.15   75.0   0.620
5         NaN    NaN    NaN   25.47          4.7  123.0   0.17  170.0     NaN
6         NaN    NaN    NaN   25.47          4.7  123.0   0.17  170.0     NaN
7       1.000  0.357  8.929   73.21          5.4   21.0   3.57  211.0     NaN
8         NaN    NaN    NaN    0.00          0.0  214.0   0.00    0.0     NaN
9         NaN    NaN    NaN   43.24          0.0    0.0   0.00   27.0   0.000
10        NaN    NaN    NaN   43.24          0.0    0.0   0.00   27.0   0.000
11        NaN    NaN    NaN   58.82          7.1  188.0   2.54    NaN     NaN
13        NaN    NaN    NaN    2.48          0.8   26.0   0.41   79.0     NaN
14        NaN    NaN    NaN    0.00          0.0  286.0   0.00    0.0     NaN
15        NaN    NaN    NaN   13.64          4.5    0.0   0.00    0.0     NaN
16        NaN    NaN    NaN   87.72          5.3   70.0   1.26    NaN     NaN
...       ...    ...    ...     ...          ...    ...    ...    ...     ...
487210    NaN    NaN    NaN    3.60          0.8    0.0   0.24    0.0     NaN
487211    NaN    NaN    NaN   60.00         14.3  229.0  10.29    NaN     NaN
487212    NaN    NaN    NaN   62.86         20.0   57.0   7.71    NaN     NaN
487213    NaN    NaN    NaN   60.00         25.7  114.0   5.14    NaN     NaN
487214    NaN    NaN    NaN   62.86         20.0   57.0   5.14    NaN     NaN
487215    NaN    NaN    NaN   60.00         25.7  171.0   7.71    NaN     NaN
487216    NaN    NaN    NaN   62.86         20.0   57.0   7.71    NaN     NaN
487217    NaN    NaN    NaN   60.00         11.4   29.0   7.71    NaN     NaN
487218    NaN    NaN    NaN    0.90          0.0    2.0   0.29    NaN     NaN
487219    NaN    NaN    NaN   26.67          0.0    0.0   0.00    NaN     NaN
487220  0.208  0.239  1.319   74.20          2.5   20.0   0.60  305.0   4.244
487221    NaN    NaN    NaN   78.95          5.3    0.0   1.89    NaN     NaN
487222    NaN    NaN    NaN   60.00         10.0    0.0   3.60    NaN     NaN
487223  0.208  0.239  1.319   74.20          2.5   20.0   0.60  305.0   4.244
487226    NaN    NaN    NaN   63.33          6.7    0.0   3.60    NaN   3.330

         Na_MG  ...  cholesterol_MG  kcal1_KCAL  protein_G  sat_fat_G  \
1        400.0  ...            47.0       194.0      18.82      2.350
2       1000.0  ...             0.0       326.0       6.52      0.000
3         62.0  ...             0.0        25.0       0.42      0.000
4         62.0  ...             0.0        25.0       0.42      0.000
5         52.0  ...            14.0       198.0       4.72      8.490
6         52.0  ...            14.0       198.0       4.72      8.490
7          0.0  ...             0.0       357.0      14.29      0.000
8       1214.0  ...            82.0       286.0      14.29     17.860
9        919.0  ...             0.0       189.0       0.00      0.000
10       919.0  ...             0.0       189.0       0.00      0.000
11       153.0  ...             0.0       447.0       9.41      4.710
13       314.0  ...             0.0        17.0       0.83      0.000
14       500.0  ...           107.0       393.0      14.29     25.000
15       682.0  ...            45.0       205.0       4.55      9.090
16       281.0  ...             0.0       368.0       5.26      0.000
...        ...  ...             ...         ...        ...        ...
487210   520.0  ...             0.0        24.0       0.40      0.000
487211    14.0  ...             0.0       343.0      22.86      0.000
487212    14.0  ...             0.0       343.0      20.00      0.000
487213     0.0  ...             0.0       343.0      22.86      0.000
487214     0.0  ...             0.0       343.0      20.00      0.000
487215    29.0  ...             0.0       343.0      22.86      0.000
487216    14.0  ...             0.0       343.0      22.86      0.000
487217     0.0  ...             0.0       343.0      25.71      0.000
487218   496.0  ...             0.0        80.0       0.00      0.000
487219  1000.0  ...             0.0       100.0       0.00      0.000
487220   227.0  ...             8.0       426.0      10.10      2.525
487221   289.0  ...             0.0       368.0      10.53      2.630
487222   500.0  ...             0.0       400.0      10.00      0.000
487223   227.0  ...             8.0       426.0      10.10      2.525
487226   250.0  ...             0.0       467.0       6.67     10.000

        total_fat_G  total_vit_d_IU  total_vit_d_UG  trans_fat_G  vit_a_IU  \
1              9.41             NaN             NaN        0.000       0.0
2              0.00             NaN             0.0        0.000       NaN
3              1.04            42.0             NaN        0.000     208.0
4              1.04            42.0             NaN        0.000     208.0
5             10.38             NaN             NaN        0.000       NaN
6             10.38             NaN             NaN        0.000       NaN
7              1.79             NaN             0.0        0.000       NaN
8             25.00             NaN             0.0        0.000       NaN
9              0.00             NaN             NaN        0.000       0.0
10             0.00             NaN             NaN        0.000       0.0
11            21.18             NaN             NaN        0.000       0.0
13             0.00             NaN             0.0        0.000       NaN
14            39.29             NaN             0.0        0.000       NaN
15            13.64             NaN             0.0        0.000       NaN
16             0.00             NaN             NaN        0.000    3947.0
...             ...             ...             ...          ...       ...
487210         0.80             0.0             NaN        0.000       NaN
487211         0.00             NaN             NaN        0.000       0.0
487212         0.00             NaN             NaN        0.000       0.0
487213         0.00             NaN             NaN        0.000       0.0
487214         0.00             NaN             NaN        0.000       0.0
487215         0.00             NaN             NaN        0.000       0.0
487216         0.00             NaN             NaN        0.000       0.0
487217         2.86             NaN             NaN        0.000       0.0
487218         0.00             NaN             NaN        0.000       0.0
487219         0.00             NaN             NaN        0.000       0.0
487220         9.70             0.0             0.0        0.012      58.0
487221         5.26             NaN             NaN        0.000       0.0
487222         5.00             NaN             NaN        0.000       0.0
487223         9.70             NaN             0.0          NaN       NaN
487226        26.67             NaN             NaN        0.000       0.0

        vit_c_MG
1            1.4
2            NaN
3            0.0
4            0.0
5            0.9
6            0.9
7            NaN
8            NaN
9            0.0
10           0.0
11           0.0
13           NaN
14           NaN
15           NaN
16           6.3
...          ...
487210       NaN
487211       0.0
487212       0.0
487213       0.0
487214       3.4
487215       3.4
487216       0.0
487217       1.7
487218       0.0
487219       0.0
487220       5.3
487221       0.0
487222      36.0
487223       5.3
487226       0.0

[372592 rows x 21 columns]

In [ ]:
k_range = range(15,31,3)

## some functions

In [ ]:
class kmeans_missing(object):
    def __init__(self,potential_centroids,n_clusters):
        #initialize with potential centroids
        self.n_clusters=n_clusters
        self.potential_centroids=potential_centroids
    def fit(self,data,max_iter=10,number_of_runs=1):
        n_clusters=self.n_clusters
        potential_centroids=self.potential_centroids

        dist_mat=np.zeros((data.shape[0],n_clusters))
        all_centroids=np.zeros((n_clusters,data.shape[1],number_of_runs))

        costs=np.zeros((number_of_runs,))
        for k in range(number_of_runs):
            idx=np.random.choice(range(potential_centroids.shape[0]),
                                 size=(n_clusters), replace=False)
            centroids=potential_centroids[idx]
            clusters=np.zeros(data.shape[0])
            old_clusters=np.zeros(data.shape[0])
            for i in range(max_iter):
                #Calc dist to centroids
                for j in range(n_clusters):
                    dist_mat[:,j]=np.nansum((data-centroids[j])**2,axis=1)
                #Assign to clusters
                clusters=np.argmin(dist_mat,axis=1)
                #Update clusters
                for j in range(n_clusters):
                    centroids[j]=np.nanmean(data[clusters==j],axis=0)
                if all(np.equal(clusters,old_clusters)):
                    break # Break when to change in clusters
                if i==max_iter-1:
                    print('no convergence before maximum iterations reached')
                else:
                    clusters,old_clusters=old_clusters,clusters

            all_centroids[:,:,k]=centroids
            costs[k]=np.mean(np.min(dist_mat,axis=1))
        self.costs=costs
        self.cost=np.min(costs)
        self.best_model=np.argmin(costs)
        self.centroids=all_centroids[:,:,self.best_model]
        self.all_centroids=all_centroids
    def predict(self,data):
        dist_mat=np.zeros((data.shape[0],self.n_clusters))
        for j in range(self.n_clusters):
            dist_mat[:,j]=np.nansum((data-self.centroids[j])**2,axis=1)
        prediction=np.argmin(dist_mat,axis=1)
        cost=np.min(dist_mat,axis=1)
        return prediction,cost

## Cluster!

In [ ]:
for k in k_range:
    kmm = kmeans_missing(X, k)
    kmm.fit(X, max_iter=200, number_of_runs=10)
    prediction, cost = kmm.predict(X)
    if len(prediction) != X_labels.shape[0]:
        print(f'kmm{k} has too many rows.')
        break
    X_labels = pd.concat([X_labels,
                      pd.Series(prediction,
                                name = f'kmm{k}',
                                index = X_labels.index)],
                     axis = 1)
    print(f'kmm{k} done')

/tmp/ipykernel_1803/4254212808.py:28: RuntimeWarning: Mean of empty slice
  centroids[j]=np.nanmean(data[clusters==j],axis=0)

kmm15 done

/tmp/ipykernel_1803/4254212808.py:28: RuntimeWarning: Mean of empty slice
  centroids[j]=np.nanmean(data[clusters==j],axis=0)

kmm18 done

/tmp/ipykernel_1803/4254212808.py:28: RuntimeWarning: Mean of empty slice
  centroids[j]=np.nanmean(data[clusters==j],axis=0)

kmm21 done

/tmp/ipykernel_1803/4254212808.py:28: RuntimeWarning: Mean of empty slice
  centroids[j]=np.nanmean(data[clusters==j],axis=0)

no convergence before maximum iterations reached
kmm24 done

/tmp/ipykernel_1803/4254212808.py:28: RuntimeWarning: Mean of empty slice
  centroids[j]=np.nanmean(data[clusters==j],axis=0)

no convergence before maximum iterations reached
kmm27 done

/tmp/ipykernel_1803/4254212808.py:28: RuntimeWarning: Mean of empty slice
  centroids[j]=np.nanmean(data[clusters==j],axis=0)

no convergence before maximum iterations reached
no convergence before maximum iterations reached
kmm30 done

In [ ]:
X_labels

,description,data_type,category,kmm15,kmm18,kmm21,kmm24,kmm27,kmm30
1,all natural gluten free chicken nuggets,branded_food,"Frozen Poultry, Chicken & Turkey",3,13,1,0,15,3
2,all natural rosemary & olive oil basmati rice...,branded_food,Flavored Rice Dishes,14,4,19,20,7,15
3,almond milk,branded_food,Plant Based Milk,8,5,12,23,5,8
4,"almond milk, original",branded_food,Plant Based Milk,8,5,12,23,5,8
5,artisan smooth & creamy gelato,branded_food,Ice Cream & Frozen Yogurt,2,7,0,8,4,18
6,"artisan smooth & creamy gelato, toasted coconut",branded_food,Ice Cream & Frozen Yogurt,2,7,0,8,4,18
7,artisanal collection spaghetti pasta,branded_food,Pasta by Shape & Type,13,4,2,19,22,24
8,authentic barrel ripened feta cheese,branded_food,Cheese,7,9,17,2,20,9
9,barbecue sauce,branded_food,"Ketchup, Mustard, BBQ & Cheese Sauce",8,5,12,23,26,22
10,"barbecue sauce, honey",branded_food,"Ketchup, Mustard, BBQ & Cheese Sauce",8,5,12,23,26,22
11,berry nut blend breakfast in the go!,branded_food,"Popcorn, Peanuts, Seeds & Related Snacks",5,3,3,3,6,6
13,blue lake cut green beans,branded_food,Canned Vegetables,8,5,12,23,5,8
14,brie triple crme soft-ripened cheese,branded_food,Cheese,12,12,17,15,17,1
15,buffalo style whipped cream cheese spread,branded_food,Cheese,2,7,0,8,4,18
16,carrot cake & frosting mix,branded_food,"Cake, Cookie & Cupcake Mixes",14,4,19,20,7,15
...,...,...,...,...,...,...,...,...,...
487210,zurek sour rye soup,branded_food,Other Soups,8,5,12,23,5,8
487211,"zursun idaho heirloom beans, anasazi beans",branded_food,Vegetable and Lentil Mixes,0,6,2,5,0,4
487212,"zursun idaho heirloom beans, christmas lima",branded_food,Vegetable and Lentil Mixes,0,6,7,5,0,4
487213,"zursun idaho heirloom beans, cranberry",branded_food,Vegetable and Lentil Mixes,0,6,7,5,0,4
487214,"zursun idaho heirloom beans, large lima beans",branded_food,Vegetable and Lentil Mixes,0,6,7,5,0,4
487215,"zursun idaho heirloom beans, trout beans",branded_food,Vegetable and Lentil Mixes,0,6,7,5,0,4
487216,"zursun idaho heirloom beans, white emergo beans",branded_food,Vegetable and Lentil Mixes,0,6,7,5,0,4
487217,"zursun idaho heirloom, red chief lentils",branded_food,Vegetable and Lentil Mixes,13,6,2,19,0,4
487218,"zw, rice cooking wine",branded_food,Other Cooking Sauces,8,5,12,23,5,8
487219,"zweigle's, hot dog sauce",branded_food,"Ketchup, Mustard, BBQ & Cheese Sauce",8,5,12,23,5,8
487220,zwieback,sr_legacy_food,3,13,4,2,19,22,24
487221,zwieback - rusk,branded_food,Crackers & Biscotti,13,4,2,19,22,24
487222,zwieback snack toast,branded_food,Crackers & Biscotti,13,4,2,19,22,24
487223,zwieback toast,survey_fndds_food,5202,13,4,2,19,22,24
487226,{trail mix},branded_food,"Popcorn, Peanuts, Seeds & Related Snacks",5,3,3,10,6,7

In [ ]:
df = pd.concat([X_labels,
                df],
               axis = 1)
df.shape

(487227, 110)

In [ ]:
df = df.loc[:, ~df.columns.duplicated()]

In [ ]:
df

,description,data_type,category,kmm15,kmm18,kmm21,kmm24,kmm27,kmm30,ALA_G,...,water_G,text,embeddings,k15,k18,k21,k24,k27,k30,k30names
1,all natural gluten free chicken nuggets,branded_food,"Frozen Poultry, Chicken & Turkey",3.0,13.0,1.0,0.0,15.0,3.0,NaN,...,NaN,all natural gluten free chicken nuggets,"[-0.038946997, -0.043313783, -0.05184707, -0.0...",3,10,10,1,8,18,poultry
2,all natural rosemary & olive oil basmati rice...,branded_food,Flavored Rice Dishes,14.0,4.0,19.0,20.0,7.0,15.0,NaN,...,NaN,"all natural rosemary olive oil basmati rice, ...","[-0.021323394, -0.0637247, 0.025973855, -0.009...",12,6,0,15,5,25,spice_herb_oil_garlic
3,almond milk,branded_food,Plant Based Milk,8.0,5.0,12.0,23.0,5.0,8.0,NaN,...,NaN,almond milk,"[-0.023772994, -0.03606859, -0.037896283, 0.08...",4,7,14,3,1,27,contains_nuts
4,"almond milk, original",branded_food,Plant Based Milk,8.0,5.0,12.0,23.0,5.0,8.0,NaN,...,NaN,"almond milk, original","[-0.07470463, 0.0006233451, -0.02409026, 0.072...",4,7,14,3,1,27,contains_nuts
5,artisan smooth & creamy gelato,branded_food,Ice Cream & Frozen Yogurt,2.0,7.0,0.0,8.0,4.0,18.0,NaN,...,NaN,artisan smooth creamy gelato,"[-0.02773605, -0.07055933, -0.024659187, 0.044...",12,17,7,0,13,22,cake_pie_waffles
6,"artisan smooth & creamy gelato, toasted coconut",branded_food,Ice Cream & Frozen Yogurt,2.0,7.0,0.0,8.0,4.0,18.0,NaN,...,NaN,"artisan smooth creamy gelato, toasted coconut","[0.013763643, -0.051946856, -0.030013578, 0.08...",6,17,7,0,13,22,cake_pie_waffles
7,artisanal collection spaghetti pasta,branded_food,Pasta by Shape & Type,13.0,4.0,2.0,19.0,22.0,24.0,NaN,...,NaN,artisanal collection spaghetti pasta,"[-0.1018854, 0.04466742, -0.041125428, 0.05308...",13,3,15,2,20,21,pastas_sauces
8,authentic barrel ripened feta cheese,branded_food,Cheese,7.0,9.0,17.0,2.0,20.0,9.0,NaN,...,NaN,authentic barrel ripened feta cheese,"[-0.027281364, 0.03043114, -0.082018316, 0.055...",0,9,20,14,17,5,cheese_in_name
9,barbecue sauce,branded_food,"Ketchup, Mustard, BBQ & Cheese Sauce",8.0,5.0,12.0,23.0,26.0,22.0,NaN,...,NaN,barbecue sauce,"[-0.066953, 0.045108773, -0.0852268, 0.0777444...",10,0,19,20,19,6,hot_bbq_ethnic_sauce
10,"barbecue sauce, honey",branded_food,"Ketchup, Mustard, BBQ & Cheese Sauce",8.0,5.0,12.0,23.0,26.0,22.0,NaN,...,NaN,"barbecue sauce, honey","[-0.05381466, 0.02960883, -0.034579657, 0.0667...",10,0,19,20,19,6,hot_bbq_ethnic_sauce
11,berry nut blend breakfast in the go!,branded_food,"Popcorn, Peanuts, Seeds & Related Snacks",5.0,3.0,3.0,3.0,6.0,6.0,NaN,...,NaN,berry nut blend breakfast in the go,"[-0.067058936, -0.031390123, -0.016046938, 0.0...",4,2,14,5,2,13,fruit_or_fruit-flavored
13,blue lake cut green beans,branded_food,Canned Vegetables,8.0,5.0,12.0,23.0,5.0,8.0,NaN,...,NaN,blue lake cut green beans,"[-0.041899018, 0.012812338, 0.024387127, -0.01...",12,6,5,12,22,23,beans_peas
14,brie triple crme soft-ripened cheese,branded_food,Cheese,12.0,12.0,17.0,15.0,17.0,1.0,NaN,...,NaN,brie triple crme soft-ripened cheese,"[-0.059584696, -0.105428606, 0.0036969674, -0....",0,9,20,14,17,5,cheese_in_name
15,buffalo style whipped cream cheese spread,branded_food,Cheese,2.0,7.0,0.0,8.0,4.0,18.0,NaN,...,NaN,buffalo style whipped cream cheese spread,"[-0.04399859, -0.07690524, -0.027361589, 0.061...",0,9,20,14,17,5,cheese_in_name
16,carrot cake & frosting mix,branded_food,"Cake, Cookie & Cupcake Mixes",14.0,4.0,19.0,20.0,7.0,15.0,NaN,...,NaN,carrot cake frosting mix,"[-0.055957615, -0.040055156, -0.0069860457, 0....",6,4,7,0,13,22,cake_pie_waffles
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487193,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"zuko, drink mix with vitamin c, grape","[-0.067004, 0.014630222, -0.06862748, 0.093395...",8,13,8,11,26,8,fruit_beverages
487194,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"zuko, drink mix with vitamin c, grape, grape","[-0.05856804, 0.010562766, -0.06412084, 0.0877...",8,13,8,11,26,8,fruit_beverages
487195,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"zuko, drink mix, orange","[-0.05902319, 0.0035241405, -0.044488035, 0.06...",8,13,8,11,26,9,sparkling_soda
487196,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"zuko, drink mix, orange, orange","[-0.03843386, -0.0030479487, -0.04236401, 0.06...",8,13,8,11,26,9,sparkling_soda
487197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"zuko, drink mix, peach","[-0.051692646, -0.02803615, -0.032832153, 0.05...",8,13,8,11,16,8,fruit_beverages
487198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"zuko, drink mix, peach, peach","[-0.036804333, -0.040234428, -0.02314205, 0.05...",8,2,8,5,16,13,fruit_or_fruit-flavored
487199,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"zuko, drink mix, pineapple","[-0.03466442, -0.009485591, -0.02100544, 0.091...",8,13,8,11,16,8,fruit_beverages
487200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"zuko, jamaica drink mix, hibiscus","[-0.016939223, 0.018708533, -0.07072977, 0.056...",8,13,8,11,26,9,sparkling_soda
487201,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"zulka, morena, pure cane sugar","[-0.09254827, 0.025600351, -0.14210962, 0.0292...",8,13,8,8,6,1,tea_coffee_drinks
487203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,zumba goma mango,"[-0.0048438357, 0.052560516, -0.009508277, 0.0...",5,14,12,16,0,19,miscellaneous2
487204,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"zumba goma, candy, watermelon","[-0.027515952, 0.024739001, 0.01924451, 0.0170...",11,1,2,10,18,26,candy
487205,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"zumba goma, candy, watermelon, watermelon","[-0.029272107, 0.012989528, 0.012816657, 0.017...",11,1,2,10,18,26,candy
487206,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,zumba pica chamoy bite candies,"[-0.06222891, 0.05078132, -0.0623587, 0.019167...",11,1,2,10,18,26,candy
487224,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"zymbom, energy drink with taurine","[-0.011939806, 0.025611171, -0.034426805, 0.05...",8,13,8,8,6,1,tea_coffee_drinks
487225,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"go bold spicy cilantro sauce, spicy cilantro","[-0.06503326, -0.067910686, -0.07530647, 0.076...",10,0,19,20,19,6,hot_bbq_ethnic_sauce

In [ ]:
df.to_parquet(data_path + 'FDCallclustered.parquet.gzip',compression = 'gzip')