In [ ]:
# link google derive drive
from google.colab import drive
drive.mount('/content/drive')
share_path = "/content/drive/MyDrive/Colab_Notebooks/deeplearning2026"
import os
print(os.listdir(share_path))

Mounted at /content/drive
['Siavash', 'NLP-Arch.gdoc', 'documentation', 'notebooks', 'data']

In [2]:
# install needed packages
!pip install sigfig

Collecting sigfig
  Downloading sigfig-1.3.19-py3-none-any.whl.metadata (4.7 kB)
Collecting sortedcontainers<3.0.0,>=2.4.0 (from sigfig)
  Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl.metadata (10 kB)
Downloading sigfig-1.3.19-py3-none-any.whl (10 kB)
Downloading sortedcontainers-2.4.0-py2.py3-none-any.whl (29 kB)
Installing collected packages: sortedcontainers, sigfig
Successfully installed sigfig-1.3.19 sortedcontainers-2.4.0

In [3]:
# prepare environment
import pandas as pd
import numpy as np
from sigfig import round

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
pd.set_option('display.min_rows', 30)

In [4]:
# load data
data_path = share_path + "/data/"

inv = pd.read_csv(data_path + 'fndds_ingredient_nutrient_value.csv',
                  usecols = [1,2,3,5],
                  dtype = {'Ingredient description': 'str',
                           'nutrient code': np.float64,
                           'nutrient value': np.float64,
                           'FDC ID': 'str'},
                  header = 0,
                  names = ['Ingredient_description',
                           'nutrient_nbr','nutrient_value',
                           'fdc_id'])


# csv crosswalk of nutrient names and codes
nut = pd.read_csv(data_path + 'nutrient.csv',
                  dtype = {'name': 'str',
                           'unit_name': 'str',
                           'nutrient_nbr': np.float64,
                           'id': 'str'},
                  header = 0,
                  names = ['nutrient_id','name','unit_name',
                           'nutrient_nbr','rank'])
nut = nut.drop('rank',axis = 1)


# list of all foods, including branded foods
food = pd.read_csv(data_path + 'food.csv',
                 usecols = ['fdc_id','description',
                            'food_category_id',
                            'data_type'],
                 dtype = {
                     'fdc_id': 'str',
                     'description': 'str',
                     'food_category_id': 'str',
                     'data_type': 'str'
                 })

fn = pd.read_csv(data_path + 'food_nutrient.csv',
                 dtype = {'fdc_id': 'str',
                          'nutrient_id': 'str',
                          'amount': np.float64},
                 header = 0,
                 names = ['id','fdc_id','nutrient_id',
                          'nutrient_value','dp','d','min','max',
                          'med','loq','foot','yr','pdv'])
fn = fn.drop(['id','dp','d','min','max','med','loq','foot','yr','pdv'],
             axis = 1)

/tmp/ipykernel_1103/2344432238.py:40: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  fn = pd.read_csv(data_path + 'food_nutrient.csv',

In [5]:
# merge
nut['nutrient_nbr'] = nut['nutrient_nbr'].astype(np.float64)
inv['nutrient_nbr'] = inv['nutrient_nbr'].astype(np.float64)
inv = pd.merge(inv, nut, how = 'right', on = 'nutrient_nbr')
nut['nutrient_id'] = nut['nutrient_id'].astype('str')
fn['nutrient_id'] = fn['nutrient_id'].astype('str')
fn = fn[fn['nutrient_id'].isin(nut['nutrient_id'])]
fn = pd.merge(fn, nut, how = 'right', on = 'nutrient_id')
fn['Ingredient_description'] = np.nan
fn = pd.concat([fn,inv])

del inv, nut

In [6]:
fn['fdc_id'] = fn['fdc_id'].astype(np.float64)
food['fdc_id'] = food['fdc_id'].astype(np.float64)
df = pd.merge(food, fn, how = 'right', on = 'fdc_id')
print(df.shape)

del food, fn

(27370184, 10)

In [7]:
df = df.dropna(subset = ['nutrient_value'])
df = df.drop(['nutrient_id', 'nutrient_nbr'], axis = 1)
print(df.shape)

(27369563, 8)

In [8]:
df.loc[df['description'].isna(), 'description'] = df.loc[df['description'].isna(), 'Ingredient_description']
df.drop(['Ingredient_description'], axis = 1, inplace = True)

In [9]:
# nutrients of interest
noi = ['Energy (Atwater General Factors)',
       'Energy (Atwater Specific Factors)',
       'Protein','Total lipid (fat)',
       'Carbohydrate, by difference',
       'Energy', 'Starch', 'Sucrose',
       'Glucose', 'Fructose', 'Lactose',
       'Maltose', 'Alcohol, ethyl',
       'Carbohydrate, by summation',
       'Water','Caffeine','Sugars, Total',
       'Fiber, total dietary','Fiber, soluble',
       'Fiber, insoluble', 'Total fat (NLEA)',
       'Calcium, Ca', 'Chlorine, Cl', 'Iron, Fe', 'Magnesium, Mg',
       'Phosphorus, P', 'Potassium, K', 'Sodium, Na', 'Sulfur, S',
       'Zinc, Zn', 'Chromium, Cr', 'Cobalt, Co', 'Copper, Cu',
       'Fluoride, F', 'Iodine, I', 'Manganese, Mn', 'Molybdenum, Mo',
       'Selenium, Se', 'Vitamin A, IU',
       'Vitamin E (alpha-tocopherol)',
       'Vitamin D (D2 + D3), International Units',
       'Vitamin D (D2 + D3)','Lycopene',
       'Boron, B', 'Nickel, Ni', 'Vitamin E',
       'Vitamin C, total ascorbic acid', 'Thiamin', 'Riboflavin',
       'Niacin', 'Pantothenic acid', 'Vitamin B-6', 'Biotin',
       'Folate, total', 'Vitamin B-12', 'Choline, total',
       'Vitamin K (Menaquinone-4)', 'Vitamin K (Dihydrophylloquinone)',
       'Vitamin K (phylloquinone)',
       'Tryptophan', 'Threonine',
       'Isoleucine', 'Leucine', 'Lysine', 'Methionine', 'Cystine',
       'Phenylalanine', 'Tyrosine', 'Valine', 'Arginine', 'Histidine',
       'Alanine', 'Aspartic acid', 'Glutamic acid', 'Glycine', 'Proline',
       'Serine', 'Hydroxyproline', 'Cysteine', 'Taurine',
       'Cholesterol', 'Fatty acids, total trans',
       'Fatty acids, total saturated', 'PUFA 20:4',
       'PUFA 22:6 n-3 (DHA)','PUFA 20:5 n-3 (EPA)',
       'PUFA 22:5 n-3 (DPA)','Fatty acids, total monounsaturated',
       'Fatty acids, total polyunsaturated',
       'PUFA 20:2 n-6 c,c','PUFA 18:2 n-6 c,c',
       'PUFA 18:3 n-6 c,c,c',
       'PUFA 18:3 n-3 c,c,c (ALA)', 'PUFA 20:3 n-3', 'PUFA 20:3 n-6',
       'PUFA 20:4 n-6','Total dietary fiber (AOAC 2011.25)']

df = df[df['name'].isin(noi)]
print(df.shape)
del noi

(24342171, 7)

In [10]:
rename = {'name': {'Total lipid (fat)': 'total_fat',
                   'Vitamin E (alpha-tocopherol)': 'alpha_tocopherol',
                   'Vitamin E (label entry primarily)': 'label_vit_e',
                   'Vitamin E': 'vit_e',
                   'Choline, total': 'total_choline',
                   'Choline, free': 'free_choline',
                   'Choline, from phosphocholine': 'phosphocholine',
                   'Choline, from phosphotidyl choline': 'phosphotidylcholine',
                   'Choline, from glycerophosphocholine': 'glycerophosphocholine',
                   'Choline, from sphingomyelin': 'sphingomyelin',
                   'Vitamin E, added': 'added_vit_e',
                   'Cholesterol': 'cholesterol',
                   'Fatty acids, total saturated': 'sat_fat',
                   'PUFA 18:2': 'LA',
                   'PUFA 18:3': 'pufa_18_3',
                   'PUFA 22:6 n-3 (DHA)': 'DHA',
                   'PUFA 20:5 n-3 (EPA)': 'EPA',
                   'PUFA 22:5 n-3 (DPA)': 'DPA',
                   'Fatty acids, total monounsaturated': 'MUFA',
                   'Fatty acids, total polyunsaturated': 'PUFA',
                   'PUFA 18:2 n-6 c,c': 'pufa_18_2_n6',
                   'PUFA 20:2 n-6 c,c': 'pufa_20_2_n6',
                   'PUFA 20:4': 'pufa_20_4',
                   'PUFA 18:3 n-6 c,c,c': 'pufa_18_3_n6',
                   'PUFA 18:3 n-3 c,c,c (ALA)': 'ALA',
                   'PUFA 20:3 n-3': 'pufa_20_3_n3',
                   'PUFA 20:3 n-6': 'pufa_20_3_n6',
                   'PUFA 20:4 n-6': 'ARA',
                   'Energy (Atwater General Factors)': 'kcal1',
                   'Energy (Atwater Specific Factors)': 'kcal2',
                   'Protein': 'protein',
                   'Carbohydrate, by difference': 'CHO1',
                   'Energy': 'kcal3',
                   'Starch': 'CHOstarch',
                   'Sucrose': 'sucrose',
                   'Glucose': 'glucose',
                   'Fructose': 'fructose',
                   'Lactose': 'lactose',
                   'Maltose': 'maltose',
                   'Alcohol, ethyl': 'alcohol',
                   'Carbohydrate, by summation': 'CHO2',
                   'Water': 'water',
                   'Caffeine': 'caffeine',
                   'Sugars, Total': 'CHOsugar',
                   'Fiber, total dietary': 'CHOfiber1',
                   'Fiber, soluble': 'sol_fiber',
                   'Fiber, insoluble': 'insol_fiber',
                   'Total fat (NLEA)': 'total_fat2',
                   'Calcium, Ca': 'Ca',
                   'Chlorine, Cl': 'Cl',
                   'Iron, Fe': 'Fe',
                   'Magnesium, Mg': 'Mg',
                   'Phosphorus, P': 'P',
                   'Potassium, K': 'K',
                   'Sodium, Na': 'Na',
                   'Sulfur, S': 'S',
                   'Zinc, Zn': 'Zn',
                   'Chromium, Cr': 'Cr',
                   'Cobalt, Co': 'Co',
                   'Copper, Cu': 'Cu',
                   'Fluoride, F': 'F',
                   'Iodine, I': 'I',
                   'Manganese, Mn': 'Mn',
                   'Molybdenum, Mo': 'Mo',
                   'Selenium, Se': 'Se',
                   'Vitamin A, IU': 'vit_a',
                   'Vitamin D (D2 + D3), International Units': 'total_vit_d',
                   'Vitamin D (D2 + D3)': 'total_vit_d',
                   'Lycopene': 'lycopene',
                   'Boron, B': 'B',
                   'Nickel, Ni': 'Ni',
                   'Vitamin C, total ascorbic acid': 'vit_c',
                   'Thiamin': 'B1',
                   'Riboflavin': 'B2',
                   'Niacin': 'B3',
                   'Pantothenic acid': 'B5',
                   'Vitamin B-6': 'B6',
                   'Biotin': 'B7',
                   'Folate, total': 'B9',
                   'Vitamin B-12': 'B12',
                   'Vitamin K (Menaquinone-4)': 'vit_k_m',
                   'Vitamin K (Dihydrophylloquinone)': 'vit_k_d',
                   'Vitamin K (phylloquinone)': 'vit_k_p',
                   'Tryptophan': 'tryptophan',
                   'Threonine': 'threonine',
                   'Isoleucine': 'isoleucine',
                   'Leucine': 'leucine',
                   'Lysine': 'lysine',
                   'Methionine': 'methionine',
                   'Cystine': 'cystine',
                   'Phenylalanine': 'phenylalanine',
                   'Tyrosine': 'tyrosine',
                   'Valine': 'valine',
                   'Arginine': 'arginine',
                   'Histidine': 'histidine',
                   'Alanine': 'alanine',
                   'Aspartic acid': 'aspartate',
                   'Glutamic acid': 'glutamate',
                   'Glycine': 'glycine',
                   'Proline': 'proline',
                   'Serine': 'serine',
                   'Hydroxyproline': 'hydroxyproline',
                   'Cysteine': 'cysteine',
                   'Taurine': 'taurine',
                   'Fatty acids, total trans': 'trans_fat',
                   'Total dietary fiber (AOAC 2011.25)': 'CHOfiber2'
                  }}

df = df.replace(rename)

In [11]:
# get rid of duplicates so we can pivot
df.drop_duplicates(inplace = True)
# the remaining duplicates have slight differences in 'nutrient_value'
# or they have different units
df[df.duplicated(subset=['fdc_id','description','name'],keep=False)].sort_values(by = ['fdc_id','name'])

,fdc_id,data_type,description,food_category_id,nutrient_value,name,unit_name
5702702,167512.0,sr_legacy_food,"Pillsbury Golden Layer Buttermilk Biscuits, Ar...",18,307.00000,kcal3,KCAL
7616965,167512.0,sr_legacy_food,"Pillsbury Golden Layer Buttermilk Biscuits, Ar...",18,1286.00000,kcal3,kJ
5702703,167513.0,sr_legacy_food,"Pillsbury, Cinnamon Rolls with Icing, refriger...",18,330.00000,kcal3,KCAL
7616966,167513.0,sr_legacy_food,"Pillsbury, Cinnamon Rolls with Icing, refriger...",18,1381.00000,kcal3,kJ
5702704,167514.0,sr_legacy_food,"Kraft Foods, Shake N Bake Original Recipe, Coa...",18,377.00000,kcal3,KCAL
7616967,167514.0,sr_legacy_food,"Kraft Foods, Shake N Bake Original Recipe, Coa...",18,1577.00000,kcal3,kJ
5702705,167515.0,sr_legacy_food,"George Weston Bakeries, Thomas English Muffins",18,232.00000,kcal3,KCAL
7616968,167515.0,sr_legacy_food,"George Weston Bakeries, Thomas English Muffins",18,972.00000,kcal3,kJ
5702706,167516.0,sr_legacy_food,"Waffles, buttermilk, frozen, ready-to-heat",18,273.00000,kcal3,KCAL
7616969,167516.0,sr_legacy_food,"Waffles, buttermilk, frozen, ready-to-heat",18,1144.00000,kcal3,kJ
5702707,167517.0,sr_legacy_food,"Waffle, buttermilk, frozen, ready-to-heat, toa...",18,309.00000,kcal3,KCAL
7616970,167517.0,sr_legacy_food,"Waffle, buttermilk, frozen, ready-to-heat, toa...",18,1291.00000,kcal3,kJ
16486757,167517.0,sr_legacy_food,"Waffle, buttermilk, frozen, ready-to-heat, toa...",18,0.00000,total_vit_d,IU
17041412,167517.0,sr_legacy_food,"Waffle, buttermilk, frozen, ready-to-heat, toa...",18,0.00000,total_vit_d,UG
5702708,167518.0,sr_legacy_food,"Waffle, buttermilk, frozen, ready-to-heat, mic...",18,289.00000,kcal3,KCAL
...,...,...,...,...,...,...,...
27361522,2647443.0,foundation_food,"Cheese, cotija, solid",1,5.93000,MUFA,G
12508283,2647443.0,foundation_food,"Cheese, cotija, solid",1,29.90000,Mg,MG
27145179,2647443.0,foundation_food,"Cheese, cotija, solid",1,30.00000,Mg,MG
12586800,2647443.0,foundation_food,"Cheese, cotija, solid",1,485.50000,P,MG
27149418,2647443.0,foundation_food,"Cheese, cotija, solid",1,486.00000,P,MG
15421755,2647443.0,foundation_food,"Cheese, cotija, solid",1,3.59700,Zn,MG
27162136,2647443.0,foundation_food,"Cheese, cotija, solid",1,3.60000,Zn,MG
21124399,2647443.0,foundation_food,"Cheese, cotija, solid",1,89.26000,cholesterol,MG
27272486,2647443.0,foundation_food,"Cheese, cotija, solid",1,89.00000,cholesterol,MG
1812951,2647443.0,foundation_food,"Cheese, cotija, solid",1,23.83568,protein,G
27098476,2647443.0,foundation_food,"Cheese, cotija, solid",1,23.84000,protein,G
24363551,2647443.0,foundation_food,"Cheese, cotija, solid",1,15.89000,sat_fat,G
27276729,2647443.0,foundation_food,"Cheese, cotija, solid",1,15.90000,sat_fat,G
17038101,2647443.0,foundation_food,"Cheese, cotija, solid",1,0.00000,total_vit_d,IU
17106760,2647443.0,foundation_food,"Cheese, cotija, solid",1,0.00000,total_vit_d,UG

In [12]:
df['nameunit'] = df['name'] + '_' + df['unit_name']
df = df.drop(['unit_name','name'], axis = 1)
df['nameunit'].sort_values().unique()

array(['ALA_G', 'ARA_G', 'B12_UG', 'B1_MG', 'B2_MG', 'B3_MG', 'B5_MG',
       'B6_MG', 'B7_UG', 'B9_UG', 'B_UG', 'CHO1_G', 'CHO2_G',
       'CHOfiber1_G', 'CHOfiber2_G', 'CHOstarch_G', 'CHOsugar_G', 'Ca_MG',
       'Cl_MG', 'Co_UG', 'Cr_UG', 'Cu_MG', 'DHA_G', 'DPA_G', 'EPA_G',
       'F_UG', 'Fe_MG', 'I_UG', 'K_MG', 'MUFA_G', 'Mg_MG', 'Mn_MG',
       'Mo_UG', 'Na_MG', 'Ni_UG', 'PUFA_G', 'P_MG', 'S_MG', 'Se_UG',
       'Zn_MG', 'alanine_G', 'alcohol_G', 'alpha_tocopherol_MG',
       'arginine_G', 'aspartate_G', 'caffeine_MG', 'cholesterol_MG',
       'cysteine_G', 'cystine_G', 'fructose_G', 'glucose_G',
       'glutamate_G', 'glycine_G', 'histidine_G', 'hydroxyproline_G',
       'insol_fiber_G', 'isoleucine_G', 'kcal1_KCAL', 'kcal2_KCAL',
       'kcal3_KCAL', 'kcal3_kJ', 'lactose_G', 'leucine_G', 'lycopene_UG',
       'lysine_G', 'maltose_G', 'methionine_G', 'phenylalanine_G',
       'proline_G', 'protein_G', 'pufa_18_2_n6_G', 'pufa_18_3_n6_G',
       'pufa_20_2_n6_G', 'pufa_20_3_n3_G', 'pufa_20_3_n6_G',
       'pufa_20_4_G', 'sat_fat_G', 'serine_G', 'sol_fiber_G', 'sucrose_G',
       'taurine_G', 'threonine_G', 'total_choline_MG', 'total_fat2_G',
       'total_fat_G', 'total_vit_d_IU', 'total_vit_d_UG', 'trans_fat_G',
       'tryptophan_G', 'tyrosine_G', 'valine_G', 'vit_a_IU', 'vit_c_MG',
       'vit_e_MG', 'vit_e_MG_ATE', 'vit_k_d_UG', 'vit_k_m_UG',
       'vit_k_p_UG', 'water_G'], dtype=object)

In [13]:
# round to 3 sig figs if duplicated, then remove
df['description'] = df['description'].str.lower()
subs = df.duplicated(subset=['fdc_id','description','nameunit'], keep=False)
df.loc[subs, 'nutrient_value'] = df.loc[subs, 'nutrient_value'].apply(lambda x: round(x, sigfigs = 3))
df.drop_duplicates(inplace = True)
# the remaining duplicates have slight differences in 'nutrient_value'
df[df.duplicated(subset=['fdc_id','description','nameunit'],keep=False)].sort_values(by = ['fdc_id','nameunit'])

/tmp/ipykernel_1103/1453687956.py:4: UserWarning: 3 significant figures requested from number with only 2 significant figures
  df.loc[subs, 'nutrient_value'] = df.loc[subs, 'nutrient_value'].apply(lambda x: round(x, sigfigs = 3))
/tmp/ipykernel_1103/1453687956.py:4: UserWarning: 3 significant figures requested from number with only 1 significant figures
  df.loc[subs, 'nutrient_value'] = df.loc[subs, 'nutrient_value'].apply(lambda x: round(x, sigfigs = 3))

,fdc_id,data_type,description,food_category_id,nutrient_value,nameunit
12447392,321358.0,foundation_food,"hummus, commercial",16,71.1,Mg_MG
27144419,321358.0,foundation_food,"hummus, commercial",16,71.0,Mg_MG
5710495,321358.0,foundation_food,"hummus, commercial",16,229.0,kcal3_KCAL
27110433,321358.0,foundation_food,"hummus, commercial",16,243.0,kcal3_KCAL
12447394,321360.0,foundation_food,"tomatoes, grape, raw",11,11.9,Mg_MG
27145130,321360.0,foundation_food,"tomatoes, grape, raw",11,12.0,Mg_MG
5710497,321360.0,foundation_food,"tomatoes, grape, raw",11,27.0,kcal3_KCAL
27111144,321360.0,foundation_food,"tomatoes, grape, raw",11,31.0,kcal3_KCAL
12447432,321611.0,foundation_food,"beans, snap, green, canned, regular pack, drai...",11,12.7,Mg_MG
27143935,321611.0,foundation_food,"beans, snap, green, canned, regular pack, drai...",11,13.0,Mg_MG
5710498,321611.0,foundation_food,"beans, snap, green, canned, regular pack, drai...",11,21.0,kcal3_KCAL
27109949,321611.0,foundation_food,"beans, snap, green, canned, regular pack, drai...",11,24.0,kcal3_KCAL
12447501,323121.0,foundation_food,"frankfurter, beef, unheated",7,11.5,Mg_MG
27143699,323121.0,foundation_food,"frankfurter, beef, unheated",7,12.0,Mg_MG
5710503,323121.0,foundation_food,"frankfurter, beef, unheated",7,314.0,kcal3_KCAL
...,...,...,...,...,...,...
27153660,2647441.0,foundation_food,"cheese, oaxaca, solid",1,81.0,K_MG
12508281,2647441.0,foundation_food,"cheese, oaxaca, solid",1,21.6,Mg_MG
27145182,2647441.0,foundation_food,"cheese, oaxaca, solid",1,22.0,Mg_MG
21124397,2647441.0,foundation_food,"cheese, oaxaca, solid",1,65.5,cholesterol_MG
27272483,2647441.0,foundation_food,"cheese, oaxaca, solid",1,66.0,cholesterol_MG
12508282,2647442.0,foundation_food,"cheese, queso fresco, solid",1,27.6,Mg_MG
27145183,2647442.0,foundation_food,"cheese, queso fresco, solid",1,28.0,Mg_MG
15278301,2647442.0,foundation_food,"cheese, queso fresco, solid",1,627.0,Na_MG
27157900,2647442.0,foundation_food,"cheese, queso fresco, solid",1,626.0,Na_MG
21124398,2647442.0,foundation_food,"cheese, queso fresco, solid",1,76.1,cholesterol_MG
27272485,2647442.0,foundation_food,"cheese, queso fresco, solid",1,76.0,cholesterol_MG
12508283,2647443.0,foundation_food,"cheese, cotija, solid",1,29.9,Mg_MG
27145179,2647443.0,foundation_food,"cheese, cotija, solid",1,30.0,Mg_MG
21124399,2647443.0,foundation_food,"cheese, cotija, solid",1,89.3,cholesterol_MG
27272486,2647443.0,foundation_food,"cheese, cotija, solid",1,89.0,cholesterol_MG

In [14]:
# round to 2 sig figs if duplicated, then remove
subs = df.duplicated(subset=['fdc_id','description','nameunit'], keep=False)
df.loc[subs, 'nutrient_value'] = df.loc[subs, 'nutrient_value'].apply(lambda x: round(x, sigfigs = 2))
df.drop_duplicates(inplace = True)

df[df.duplicated(subset=['fdc_id','description','nameunit'],keep=False)].sort_values(by = ['fdc_id','nameunit'])

/tmp/ipykernel_1103/185672087.py:3: UserWarning: 2 significant figures requested from number with only 1 significant figures
  df.loc[subs, 'nutrient_value'] = df.loc[subs, 'nutrient_value'].apply(lambda x: round(x, sigfigs = 2))

,fdc_id,data_type,description,food_category_id,nutrient_value,nameunit
5710495,321358.0,foundation_food,"hummus, commercial",16,230.000,kcal3_KCAL
27110433,321358.0,foundation_food,"hummus, commercial",16,240.000,kcal3_KCAL
5710497,321360.0,foundation_food,"tomatoes, grape, raw",11,27.000,kcal3_KCAL
27111144,321360.0,foundation_food,"tomatoes, grape, raw",11,31.000,kcal3_KCAL
5710498,321611.0,foundation_food,"beans, snap, green, canned, regular pack, drai...",11,21.000,kcal3_KCAL
27109949,321611.0,foundation_food,"beans, snap, green, canned, regular pack, drai...",11,24.000,kcal3_KCAL
5710506,323505.0,foundation_food,"kale, raw",11,35.000,kcal3_KCAL
27109993,323505.0,foundation_food,"kale, raw",11,43.000,kcal3_KCAL
12447662,324653.0,foundation_food,"pickles, cucumber, dill or kosher dill",11,7.100,Mg_MG
27144082,324653.0,foundation_food,"pickles, cucumber, dill or kosher dill",11,7.000,Mg_MG
5710513,324653.0,foundation_food,"pickles, cucumber, dill or kosher dill",11,12.000,kcal3_KCAL
27110096,324653.0,foundation_food,"pickles, cucumber, dill or kosher dill",11,14.000,kcal3_KCAL
12447725,325287.0,foundation_food,"grapefruit juice, white, canned or bottled, un...",9,9.600,Mg_MG
27143781,325287.0,foundation_food,"grapefruit juice, white, canned or bottled, un...",9,10.000,Mg_MG
5710517,325287.0,foundation_food,"grapefruit juice, white, canned or bottled, un...",9,37.000,kcal3_KCAL
...,...,...,...,...,...,...
27136259,2512380.0,foundation_food,"rice, brown, long grain, unenriched, raw",20,8.000,Ca_MG
9040390,2512381.0,foundation_food,"rice, white, long grain, unenriched, raw",20,0.150,CHOfiber1_G
27132440,2512381.0,foundation_food,"rice, white, long grain, unenriched, raw",20,0.100,CHOfiber1_G
10674373,2512381.0,foundation_food,"rice, white, long grain, unenriched, raw",20,4.500,Ca_MG
27136686,2512381.0,foundation_food,"rice, white, long grain, unenriched, raw",20,4.000,Ca_MG
15151821,2512381.0,foundation_food,"rice, white, long grain, unenriched, raw",20,0.460,Na_MG
27157882,2512381.0,foundation_food,"rice, white, long grain, unenriched, raw",20,0.000,Na_MG
15278296,2647437.0,foundation_food,"yogurt, plain, nonfat",1,52.000,Na_MG
27157895,2647437.0,foundation_food,"yogurt, plain, nonfat",1,51.000,Na_MG
21124393,2647437.0,foundation_food,"yogurt, plain, nonfat",1,3.400,cholesterol_MG
27272478,2647437.0,foundation_food,"yogurt, plain, nonfat",1,3.000,cholesterol_MG
3686596,2647437.0,foundation_food,"yogurt, plain, nonfat",1,0.088,total_fat_G
27102713,2647437.0,foundation_food,"yogurt, plain, nonfat",1,0.090,total_fat_G
17106754,2647437.0,foundation_food,"yogurt, plain, nonfat",1,0.220,total_vit_d_UG
27196058,2647437.0,foundation_food,"yogurt, plain, nonfat",1,0.200,total_vit_d_UG

In [15]:
# won't take the remaining duplicates down to 1 sig fig
# instead, I'll drop the second row
df.drop_duplicates(subset=['fdc_id','description','nameunit'], inplace = True)
df.shape

(24191496, 6)

In [16]:
df = df.pivot(index = ['fdc_id','description','food_category_id','data_type'],
              columns = 'nameunit',
              values = 'nutrient_value')
df

nameunit                                                                                       ALA_G  \
fdc_id    description                                        food_category_id data_type
NaN       almond butter, creamy                              NaN              NaN                NaN
          apples, fuji, with skin, raw                       NaN              NaN                NaN
          apples, gala, with skin, raw                       NaN              NaN                NaN
          apples, granny smith, with skin, raw               NaN              NaN                NaN
          apples, honeycrisp, with skin, raw                 NaN              NaN                NaN
          apples, red delicious, with skin, raw              NaN              NaN                NaN
          applesauce, unsweetened, with added vitamin c      NaN              NaN                NaN
          babyfood, cereal, barley, dry fortified            NaN              NaN                NaN
          babyfood, cereal, oatmeal, dry fortified           NaN              NaN                NaN
          babyfood, cereal, rice, dry fortified              NaN              NaN                NaN
          babyfood, gerber, graduates lil biscuits vanill... NaN              NaN                NaN
          babyfood, juice, apple                             NaN              NaN                NaN
          babyfood, multigrain whole grain cereal, dry fo... NaN              NaN                NaN
          bagels, plain, enriched, with calcium propionat... NaN              NaN                NaN
          bagels, wheat                                      NaN              NaN                NaN
...                                                                                              ...
2751489.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751490.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751491.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751492.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751493.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751494.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751495.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751496.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751497.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751498.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751499.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751500.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751501.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751502.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751503.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN

nameunit                                                                                       ARA_G  \
fdc_id    description                                        food_category_id data_type
NaN       almond butter, creamy                              NaN              NaN                NaN
          apples, fuji, with skin, raw                       NaN              NaN                NaN
          apples, gala, with skin, raw                       NaN              NaN                NaN
          apples, granny smith, with skin, raw               NaN              NaN                NaN
          apples, honeycrisp, with skin, raw                 NaN              NaN                NaN
          apples, red delicious, with skin, raw              NaN              NaN                NaN
          applesauce, unsweetened, with added vitamin c      NaN              NaN                NaN
          babyfood, cereal, barley, dry fortified            NaN              NaN                NaN
          babyfood, cereal, oatmeal, dry fortified           NaN              NaN                NaN
          babyfood, cereal, rice, dry fortified              NaN              NaN                NaN
          babyfood, gerber, graduates lil biscuits vanill... NaN              NaN                NaN
          babyfood, juice, apple                             NaN              NaN                NaN
          babyfood, multigrain whole grain cereal, dry fo... NaN              NaN                NaN
          bagels, plain, enriched, with calcium propionat... NaN              NaN                NaN
          bagels, wheat                                      NaN              NaN                NaN
...                                                                                              ...
2751489.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751490.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751491.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751492.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751493.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751494.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751495.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751496.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751497.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751498.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751499.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751500.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751501.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751502.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751503.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN

nameunit                                                                                       B12_UG  \
fdc_id    description                                        food_category_id data_type
NaN       almond butter, creamy                              NaN              NaN                 NaN
          apples, fuji, with skin, raw                       NaN              NaN                 0.0
          apples, gala, with skin, raw                       NaN              NaN                 0.0
          apples, granny smith, with skin, raw               NaN              NaN                 0.0
          apples, honeycrisp, with skin, raw                 NaN              NaN                 0.0
          apples, red delicious, with skin, raw              NaN              NaN                 0.0
          applesauce, unsweetened, with added vitamin c      NaN              NaN                 NaN
          babyfood, cereal, barley, dry fortified            NaN              NaN                 0.8
          babyfood, cereal, oatmeal, dry fortified           NaN              NaN                 0.8
          babyfood, cereal, rice, dry fortified              NaN              NaN                 0.8
          babyfood, gerber, graduates lil biscuits vanill... NaN              NaN                 NaN
          babyfood, juice, apple                             NaN              NaN                 NaN
          babyfood, multigrain whole grain cereal, dry fo... NaN              NaN                 0.8
          bagels, plain, enriched, with calcium propionat... NaN              NaN                 NaN
          bagels, wheat                                      NaN              NaN                 NaN
...                                                                                               ...
2751489.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food     NaN
2751490.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food     NaN
2751491.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food     NaN
2751492.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food     NaN
2751493.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food     NaN
2751494.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food     NaN
2751495.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food     NaN
2751496.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food     NaN
2751497.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food     NaN
2751498.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food     NaN
2751499.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food     NaN
2751500.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food     NaN
2751501.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food     NaN
2751502.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food     NaN
2751503.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food     NaN

nameunit                                                                                       B1_MG  \
fdc_id    description                                        food_category_id data_type
NaN       almond butter, creamy                              NaN              NaN                NaN
          apples, fuji, with skin, raw                       NaN              NaN                NaN
          apples, gala, with skin, raw                       NaN              NaN                NaN
          apples, granny smith, with skin, raw               NaN              NaN                NaN
          apples, honeycrisp, with skin, raw                 NaN              NaN                NaN
          apples, red delicious, with skin, raw              NaN              NaN                NaN
          applesauce, unsweetened, with added vitamin c      NaN              NaN                NaN
          babyfood, cereal, barley, dry fortified            NaN              NaN                NaN
          babyfood, cereal, oatmeal, dry fortified           NaN              NaN                NaN
          babyfood, cereal, rice, dry fortified              NaN              NaN                NaN
          babyfood, gerber, graduates lil biscuits vanill... NaN              NaN                NaN
          babyfood, juice, apple                             NaN              NaN                NaN
          babyfood, multigrain whole grain cereal, dry fo... NaN              NaN                NaN
          bagels, plain, enriched, with calcium propionat... NaN              NaN                NaN
          bagels, wheat                                      NaN              NaN                NaN
...                                                                                              ...
2751489.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751490.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751491.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751492.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751493.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751494.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751495.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751496.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751497.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751498.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751499.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751500.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751501.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751502.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751503.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN

nameunit                                                                                       B2_MG  \
fdc_id    description                                        food_category_id data_type
NaN       almond butter, creamy                              NaN              NaN                NaN
          apples, fuji, with skin, raw                       NaN              NaN                NaN
          apples, gala, with skin, raw                       NaN              NaN                NaN
          apples, granny smith, with skin, raw               NaN              NaN                NaN
          apples, honeycrisp, with skin, raw                 NaN              NaN                NaN
          apples, red delicious, with skin, raw              NaN              NaN                NaN
          applesauce, unsweetened, with added vitamin c      NaN              NaN                NaN
          babyfood, cereal, barley, dry fortified            NaN              NaN                NaN
          babyfood, cereal, oatmeal, dry fortified           NaN              NaN                NaN
          babyfood, cereal, rice, dry fortified              NaN              NaN                NaN
          babyfood, gerber, graduates lil biscuits vanill... NaN              NaN                NaN
          babyfood, juice, apple                             NaN              NaN                NaN
          babyfood, multigrain whole grain cereal, dry fo... NaN              NaN                NaN
          bagels, plain, enriched, with calcium propionat... NaN              NaN                NaN
          bagels, wheat                                      NaN              NaN                NaN
...                                                                                              ...
2751489.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751490.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751491.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751492.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751493.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751494.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751495.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751496.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751497.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751498.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751499.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751500.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751501.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751502.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751503.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN

nameunit                                                                                       B3_MG  \
fdc_id    description                                        food_category_id data_type
NaN       almond butter, creamy                              NaN              NaN                NaN
          apples, fuji, with skin, raw                       NaN              NaN                NaN
          apples, gala, with skin, raw                       NaN              NaN                NaN
          apples, granny smith, with skin, raw               NaN              NaN                NaN
          apples, honeycrisp, with skin, raw                 NaN              NaN                NaN
          apples, red delicious, with skin, raw              NaN              NaN                NaN
          applesauce, unsweetened, with added vitamin c      NaN              NaN                NaN
          babyfood, cereal, barley, dry fortified            NaN              NaN                NaN
          babyfood, cereal, oatmeal, dry fortified           NaN              NaN                NaN
          babyfood, cereal, rice, dry fortified              NaN              NaN                NaN
          babyfood, gerber, graduates lil biscuits vanill... NaN              NaN                NaN
          babyfood, juice, apple                             NaN              NaN                NaN
          babyfood, multigrain whole grain cereal, dry fo... NaN              NaN                NaN
          bagels, plain, enriched, with calcium propionat... NaN              NaN                NaN
          bagels, wheat                                      NaN              NaN                NaN
...                                                                                              ...
2751489.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751490.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751491.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751492.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751493.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751494.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751495.0 green onion, (scallion), bulb and greens, root ... NaN              sub_sample_food    NaN
2751496.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751497.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751498.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751499.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751500.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751501.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751502.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN
2751503.0 shallots, bulb, peeled, root removed, raw          NaN              sub_sample_food    NaN


In [17]:
df.columns.sort_values()

Index(['ALA_G', 'ARA_G', 'B12_UG', 'B1_MG', 'B2_MG', 'B3_MG', 'B5_MG', 'B6_MG',
       'B7_UG', 'B9_UG', 'B_UG', 'CHO1_G', 'CHO2_G', 'CHOfiber1_G',
       'CHOfiber2_G', 'CHOstarch_G', 'CHOsugar_G', 'Ca_MG', 'Cl_MG', 'Co_UG',
       'Cr_UG', 'Cu_MG', 'DHA_G', 'DPA_G', 'EPA_G', 'F_UG', 'Fe_MG', 'I_UG',
       'K_MG', 'MUFA_G', 'Mg_MG', 'Mn_MG', 'Mo_UG', 'Na_MG', 'Ni_UG', 'PUFA_G',
       'P_MG', 'S_MG', 'Se_UG', 'Zn_MG', 'alanine_G', 'alcohol_G',
       'alpha_tocopherol_MG', 'arginine_G', 'aspartate_G', 'caffeine_MG',
       'cholesterol_MG', 'cysteine_G', 'cystine_G', 'fructose_G', 'glucose_G',
       'glutamate_G', 'glycine_G', 'histidine_G', 'hydroxyproline_G',
       'insol_fiber_G', 'isoleucine_G', 'kcal1_KCAL', 'kcal2_KCAL',
       'kcal3_KCAL', 'kcal3_kJ', 'lactose_G', 'leucine_G', 'lycopene_UG',
       'lysine_G', 'maltose_G', 'methionine_G', 'phenylalanine_G', 'proline_G',
       'protein_G', 'pufa_18_2_n6_G', 'pufa_18_3_n6_G', 'pufa_20_2_n6_G',
       'pufa_20_3_n3_G', 'pufa_20_3_n6_G', 'pufa_20_4_G', 'sat_fat_G',
       'serine_G', 'sol_fiber_G', 'sucrose_G', 'taurine_G', 'threonine_G',
       'total_choline_MG', 'total_fat2_G', 'total_fat_G', 'total_vit_d_IU',
       'total_vit_d_UG', 'trans_fat_G', 'tryptophan_G', 'tyrosine_G',
       'valine_G', 'vit_a_IU', 'vit_c_MG', 'vit_e_MG', 'vit_e_MG_ATE',
       'vit_k_d_UG', 'vit_k_m_UG', 'vit_k_p_UG', 'water_G'],
      dtype='object', name='nameunit')

In [18]:
# condense duplicated nutrients
# condense the many vit E columns
vit_E = ['alpha_tocopherol_MG','vit_e_MG','vit_e_MG_ATE']
df['total_vit_e_mg'] = df[vit_E].sum(axis = 1, skipna = True)
df.loc[df[vit_E].isna().sum(axis=1) == len(vit_E), 'total_vit_e_mg'] = np.nan
df.drop(vit_E, axis = 1, inplace = True)

In [19]:
# condense carbohydrates
df.loc[df['CHO1_G'].isna(), 'CHO1_G'] = df.loc[df['CHO1_G'].isna(), 'CHO2_G']
df.drop('CHO2_G', axis = 1, inplace = True)

# condense fiber columns
df.loc[df['CHOfiber1_G'].isna(), 'CHOfiber1_G'] = df.loc[df['CHOfiber1_G'].isna(), 'CHOfiber2_G']
df.drop('CHOfiber2_G', axis = 1, inplace = True)

# condense energy columns
df.loc[df['kcal1_KCAL'].isna(), 'kcal1_KCAL'] = df.loc[df['kcal1_KCAL'].isna(), 'kcal2_KCAL']
df.drop('kcal2_KCAL', axis = 1, inplace = True)
df.loc[df['kcal1_KCAL'].isna(), 'kcal1_KCAL'] = df.loc[df['kcal1_KCAL'].isna(), 'kcal3_KCAL']
df.drop(['kcal3_KCAL','kcal3_kJ'], axis = 1, inplace = True)

# condense total fat columns
df.loc[df['total_fat_G'].isna(), 'total_fat_G'] = df.loc[df['total_fat_G'].isna(), 'total_fat2_G']
df.drop('total_fat2_G', axis = 1, inplace = True)

# add up vitamin K columns
ks = ['vit_k_d_UG', 'vit_k_m_UG', 'vit_k_p_UG']
df['vit_k_UG'] = df[ks].sum(axis = 1)
df.loc[df[ks].isna().sum(axis=1) == len(ks), 'vit_k_UG'] = np.nan
df.drop(ks, axis = 1, inplace=True)

In [20]:
# many rows are the same food with different fdc_id
df = df.reset_index(names=['fdc_id', 'description','category','data_type'])
(df.loc[df.duplicated(subset=['description'],keep=False),
 ['fdc_id','description','category','data_type']]
 .sort_values(by = ['description']))

nameunit,fdc_id,description,category,data_type
1948417,2742400.0,advancepierre flamebroiled rib shaped pork pa...,Meat/Poultry/Other Animals - Prepared/Processed,branded_food
1943455,2737438.0,advancepierre flamebroiled rib shaped pork pa...,Meat/Poultry/Other Animals - Prepared/Processed,branded_food
1908359,2700133.0,advancepierre flamebroiled rib shaped pork pa...,Meat/Poultry/Other Animals - Prepared/Processed,branded_food
1940278,2734261.0,advancepierre flamebroiled rib shaped pork pa...,Meat/Poultry/Other Animals - Prepared/Processed,branded_food
1782528,2571794.0,all natural gluten free chicken nuggets,"Frozen Poultry, Chicken & Turkey",branded_food
1744193,2533357.0,all natural gluten free chicken nuggets,"Frozen Poultry, Chicken & Turkey",branded_food
1827653,2617100.0,all natural gluten free chicken nuggets,"Frozen Poultry, Chicken & Turkey",branded_food
1815065,2604504.0,all natural rosemary & olive oil basmati rice...,Flavored Rice Dishes,branded_food
1793660,2583001.0,all natural rosemary & olive oil basmati rice...,Flavored Rice Dishes,branded_food
875282,1568995.0,almond milk,Plant Based Milk,branded_food
642833,1276906.0,almond milk,Plant Based Milk,branded_food
958542,1657973.0,artisan smooth & creamy gelato,Ice Cream & Frozen Yogurt,branded_food
712748,1365768.0,artisan smooth & creamy gelato,Ice Cream & Frozen Yogurt,branded_food
1817670,2607109.0,authentic barrel ripened feta cheese,Cheese,branded_food
1794631,2583972.0,authentic barrel ripened feta cheese,Cheese,branded_food
...,...,...,...,...
1307112,2025991.0,zwieback - rusk,Crackers & Biscotti,branded_food
575156,1199791.0,zwieback - rusk,Crackers & Biscotti,branded_food
798502,1491838.0,zwieback - rusk,Crackers & Biscotti,branded_food
1292279,2010537.0,zwieback snack toast,Crackers & Biscotti,branded_food
774026,1467078.0,zwieback snack toast,Crackers & Biscotti,branded_food
469551,1055329.0,zwieback snack toast,Crackers & Biscotti,branded_food
107555,435534.0,"zymbom, energy drink with taurine",Soda,branded_food
1703030,2491017.0,"zymbom, energy drink with taurine",Soda,branded_food
1577738,2364726.0,"zymbom, energy drink with taurine",Soda,branded_food
840689,1534324.0,"zymbom, energy drink with taurine",Soda,branded_food
1332428,2051714.0,"zymbom, energy drink with taurine",Soda,branded_food
164410,492509.0,{trail mix},"Popcorn, Peanuts, Seeds & Related Snacks",branded_food
1361487,2081522.0,{trail mix},"Popcorn, Peanuts, Seeds & Related Snacks",branded_food
889205,1583012.0,{trail mix},"Popcorn, Peanuts, Seeds & Related Snacks",branded_food
654920,1290905.0,{trail mix},"Popcorn, Peanuts, Seeds & Related Snacks",branded_food

In [21]:
# coalesce all non-missing values from the duplicates into one row.
# takes > 20 mins
df = df.drop('fdc_id', axis = 1)

id_cols = ['description']          # columns defining duplicates
value_cols = df.columns.difference(id_cols)

def first_non_null(s):
    return s.dropna().iloc[0] if s.notna().any() else pd.NA

df = (
    df.groupby(id_cols, as_index=False)
      .agg({col: first_non_null for col in value_cols})
)

df

nameunit,description,ALA_G,ARA_G,B12_UG,B1_MG,B2_MG,B3_MG,B5_MG,B6_MG,B7_UG,B9_UG,B_UG,CHO1_G,CHOfiber1_G,CHOstarch_G,CHOsugar_G,Ca_MG,Cl_MG,Co_UG,Cr_UG,Cu_MG,DHA_G,DPA_G,EPA_G,F_UG,Fe_MG,I_UG,K_MG,MUFA_G,Mg_MG,Mn_MG,Mo_UG,Na_MG,Ni_UG,PUFA_G,P_MG,S_MG,Se_UG,Zn_MG,alanine_G,alcohol_G,arginine_G,aspartate_G,caffeine_MG,category,cholesterol_MG,cysteine_G,cystine_G,data_type,fructose_G,glucose_G,glutamate_G,glycine_G,histidine_G,hydroxyproline_G,insol_fiber_G,isoleucine_G,kcal1_KCAL,lactose_G,leucine_G,lycopene_UG,lysine_G,maltose_G,methionine_G,phenylalanine_G,proline_G,protein_G,pufa_18_2_n6_G,pufa_18_3_n6_G,pufa_20_2_n6_G,pufa_20_3_n3_G,pufa_20_3_n6_G,pufa_20_4_G,sat_fat_G,serine_G,sol_fiber_G,sucrose_G,taurine_G,threonine_G,total_choline_MG,total_fat_G,total_vit_d_IU,total_vit_d_UG,total_vit_e_mg,trans_fat_G,tryptophan_G,tyrosine_G,valine_G,vit_a_IU,vit_c_MG,vit_k_UG,water_G
0,advancepierre flamebroiled rib shaped pork pa...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,10.17,1.0,<NA>,<NA>,41.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.2,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,288.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Meat/Poultry/Other Animals - Prepared/Processed,45.0,<NA>,<NA>,branded_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,209.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,14.77,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4.13,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,12.1,<NA>,<NA>,<NA>,0.09,<NA>,<NA>,<NA>,<NA>,1.8,<NA>,<NA>
1,all natural gluten free chicken nuggets,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,8.24,0.0,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.85,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,400.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"Frozen Poultry, Chicken & Turkey",47.0,<NA>,<NA>,branded_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,194.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,18.82,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2.35,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,9.41,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,0.0,1.4,<NA>,<NA>
2,all natural rosemary & olive oil basmati rice...,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,78.26,2.2,<NA>,<NA>,22.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.04,<NA>,87.0,<NA>,<NA>,<NA>,<NA>,1000.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Flavored Rice Dishes,0.0,<NA>,<NA>,branded_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,326.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,6.52,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,0.0,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
3,almond milk,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.33,0.4,<NA>,<NA>,42.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.15,<NA>,75.0,0.62,<NA>,<NA>,<NA>,62.0,<NA>,0.21,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Plant Based Milk,0.0,<NA>,<NA>,branded_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,25.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.42,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.04,42.0,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,208.0,0.0,<NA>,<NA>
4,"almond milk, original",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.33,0.4,<NA>,<NA>,42.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.15,<NA>,75.0,0.62,<NA>,<NA>,<NA>,62.0,<NA>,0.21,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Plant Based Milk,0.0,<NA>,<NA>,branded_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,25.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.42,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.04,42.0,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,208.0,0.0,<NA>,<NA>
5,artisan smooth & creamy gelato,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,25.47,4.7,<NA>,<NA>,123.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.17,<NA>,170.0,<NA>,<NA>,<NA>,<NA>,52.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Ice Cream & Frozen Yogurt,14.0,<NA>,<NA>,branded_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,198.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4.72,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,8.49,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,10.38,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,0.9,<NA>,<NA>
6,"artisan smooth & creamy gelato, toasted coconut",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,25.47,4.7,<NA>,<NA>,123.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.17,<NA>,170.0,<NA>,<NA>,<NA>,<NA>,52.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Ice Cream & Frozen Yogurt,14.0,<NA>,<NA>,branded_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,198.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4.72,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,8.49,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,10.38,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,0.9,<NA>,<NA>
7,artisanal collection spaghetti pasta,<NA>,<NA>,<NA>,1.0,0.357,8.929,<NA>,<NA>,<NA>,355.0,<NA>,73.21,5.4,<NA>,<NA>,21.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.57,<NA>,211.0,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Pasta by Shape & Type,0.0,<NA>,<NA>,branded_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2.0,<NA>,357.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,14.29,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,4.0,<NA>,<NA>,<NA>,<NA>,1.79,<NA>,0.0,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
8,authentic barrel ripened feta cheese,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,0.0,<NA>,<NA>,214.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,1214.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cheese,82.0,<NA>,<NA>,branded_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,286.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,14.29,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,17.86,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,25.0,<NA>,0.0,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
9,barbecue sauce,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,43.24,0.0,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,27.0,0.0,<NA>,<NA>,<NA>,919.0,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"Ketchup, Mustard, BBQ & Cheese Sauce",0.0,<NA>,<NA>,branded_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,189.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,0.0,0.0,<NA>,<NA>
10,"barbecue sauce, honey",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,43.24,0.0,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,27.0,0.0,<NA>,<NA>,<NA>,919.0,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"Ketchup, Mustard, BBQ & Cheese Sauce",0.0,<NA>,<NA>,branded_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,189.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,0.0,0.0,<NA>,<NA>
11,berry nut blend breakfast in the go!,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,58.82,7.1,<NA>,<NA>,188.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2.54,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,153.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"Popcorn, Peanuts, Seeds & Related Snacks",0.0,<NA>,<NA>,branded_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,447.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,9.41,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4.71,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,21.18,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,0.0,0.0,<NA>,<NA>
12,"black cherry pure energy seltzer, black cherry",<NA>,<NA>,1.35,<NA>,<NA>,4.507,1.127,0.451,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,2.11,<NA>,<NA>,<NA>,<NA>,<NA>,Soda,<NA>,<NA>,<NA>,branded_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,4.2,<NA>,<NA>
13,blue lake cut green beans,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2.48,0.8,<NA>,<NA>,26.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.41,<NA>,79.0,<NA>,<NA>,<NA>,<NA>,314.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Canned Vegetables,0.0,<NA>,<NA>,branded_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,17.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.83,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,0.0,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
14,brie triple crme soft-ripened cheese,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,0.0,<NA>,<NA>,286.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,500.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Cheese,107.0,<NA>,<NA>,branded_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,393.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,14.29,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,25.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,39.29,<NA>,0.0,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
487212,"zursun idaho heirloom beans, christmas lima",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,62.86,20.0,<NA>,<NA>,57.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,7.71,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,14.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Vegetable and Lentil Mixes,0.0,<NA>,<NA>,branded_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,343.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,20.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,0.0,0.0,<NA>,<NA>
487213,"zursun idaho heirloom beans, cranberry",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,60.0,25.7,<NA>,<NA>,114.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,5.14,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Vegetable and Lentil Mixes,0.0,<NA>,<NA>,branded_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,343.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,22.86,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,0.0,0.0,<NA>,<NA>
487214,"zursun idaho heirloom beans, large lima beans",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,62.86,20.0,<NA>,<NA>,57.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,5.14,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Vegetable and Lentil Mixes,0.0,<NA>,<NA>,branded_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,343.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,20.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,0.0,3.4,<NA>,<NA>
487215,"zursun idaho heirloom beans, trout beans",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,60.0,25.7,<NA>,<NA>,171.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,7.71,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,29.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Vegetable and Lentil Mixes,0.0,<NA>,<NA>,branded_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,343.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,22.86,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,0.0,3.4,<NA>,<NA>
487216,"zursun idaho heirloom beans, white emergo beans",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,62.86,20.0,<NA>,<NA>,57.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,7.71,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,14.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Vegetable and Lentil Mixes,0.0,<NA>,<NA>,branded_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,343.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,22.86,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,0.0,0.0,<NA>,<NA>
487217,"zursun idaho heirloom, red chief lentils",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,60.0,11.4,<NA>,<NA>,29.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,7.71,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Vegetable and Lentil Mixes,0.0,<NA>,<NA>,branded_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,343.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,25.71,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2.86,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,0.0,1.7,<NA>,<NA>
487218,"zw, rice cooking wine",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.9,0.0,<NA>,<NA>,2.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.29,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,496.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Other Cooking Sauces,0.0,<NA>,<NA>,branded_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,80.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,0.0,0.0,<NA>,<NA>
487219,"zweigle's, hot dog sauce",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,26.67,0.0,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1000.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"Ketchup, Mustard, BBQ & Cheese Sauce",0.0,<NA>,<NA>,branded_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,100.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,0.0,0.0,<NA>,<NA>
487220,zwieback,<NA>,<NA>,0.0,0.208,0.239,1.319,0.537,0.082,<NA>,87.0,<NA>,74.2,2.5,<NA>,<NA>,20.0,<NA>,<NA>,<NA>,0.145,0.0,0.0,0.0,0.1,0.6,<NA>,305.0,4.244,14.0,<NA>,<NA>,227.0,<NA>,2.073,55.0,<NA>,28.7,0.54,<NA>,0.0,<NA>,<NA>,0.0,3,8.0,<NA>,<NA>,sr_legacy_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,426.0,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,10.1,<NA>,<NA>,0.0,<NA>,<NA>,0.001,2.525,<NA>,<NA>,<NA>,<NA>,<NA>,10.7,9.7,0.0,0.0,2.44,0.012,<NA>,<NA>,<NA>,58.0,5.3,0.9,4.5
487221,zwieback - rusk,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,78.95,5.3,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,1.89,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,289.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Crackers & Biscotti,0.0,<NA>,<NA>,branded_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,368.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,10.53,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,2.63,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,5.26,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,0.0,0.0,<NA>,<NA>
487222,zwieback snack toast,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,60.0,10.0,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.6,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,500.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Crackers & Biscotti,0.0,<NA>,<NA>,branded_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,400.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,10.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,5.0,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,0.0,36.0,<NA>,<NA>
487223,zwieback toast,<NA>,<NA>,0.0,0.208,0.239,1.319,<NA>,0.082,<NA>,87.0,<NA>,74.2,2.5,<NA>,<NA>,20.0,<NA>,<NA>,<NA>,0.145,0.0,0.0,0.0,<NA>,0.6,<NA>,305.0,4.244,14.0,<NA>,<NA>,227.0,<NA>,2.073,55.0,<NA>,28.7,0.54,<NA>,0.0,<NA>,<NA>,0.0,5202,8.0,<NA>,<NA>,survey_fndds_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,426.0,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,10.1,<NA>,<NA>,<NA>,<NA>,<NA>,0.001,2.525,<NA>,<NA>,<NA>,<NA>,<NA>,10.7,9.7,<NA>,0.0,2.44,<NA>,<NA>,<NA>,<NA>,<NA>,5.3,0.9,4.5
487224,"zymbom, energy drink with taurine",<NA>,<NA>,9.6,<NA>,<NA>,10.0,3.6,2.4,<NA>,<NA>,<NA>,11.2,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,80.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Soda,<NA>,<NA>,<NA>,branded_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,44.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.4,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
487225,"{go bold} spicy cilantro sauce, spicy cilantro",<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,7.14,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,714.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,Other Cooking Sauces,36.0,<NA>,<NA>,branded_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,643.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,10.71,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,71.43,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>
487226,{trail mix},<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,63.33,6.7,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,3.6,<NA>,<NA>,3.33,<NA>,<NA>,<NA>,250.0,<NA>,8.33,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,"Popcorn, Peanuts, Seeds & Related Snacks",0.0,<NA>,<NA>,branded_food,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,467.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,6.67,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,10.0,<NA>,<NA>,<NA>,<NA>,<NA>,<NA>,26.67,<NA>,<NA>,<NA>,0.0,<NA>,<NA>,<NA>,0.0,0.0,<NA>,<NA>

In [22]:
df.to_parquet(data_path + 'FDCeverything.parquet.gzip',compression = 'gzip')